// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlounprhypvctkbsrhli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsb3VucHJoeXB2Y3RrYnNyaGxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTM3OTEsImV4cCI6MjA3Mjc4OTc5MX0.o2ydckxipoGJoCM4fojuxq9A4DXYWhpfJGRGZPRXqzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});